/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-24-2015
 * 
 * XDoclet definition:
 * @struts.form name="booking1Form"
 */
public class Booking1Form extends ActionForm {
	/*
	 * Generated fields
	 */

	/** date_check_out property */
	private String date_check_out;

	/** date_check_in property */
	private String date_check_in;

	/** people_booking property */
	private String people_booking;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the date_check_out.
	 * @return String
	 */
	public String getDate_check_out() {
		return date_check_out;
	}

	/** 
	 * Set the date_check_out.
	 * @param date_check_out The date_check_out to set
	 */
	public void setDate_check_out(String date_check_out) {
		this.date_check_out = date_check_out;
	}

	/** 
	 * Returns the date_check_in.
	 * @return String
	 */
	public String getDate_check_in() {
		return date_check_in;
	}

	/** 
	 * Set the date_check_in.
	 * @param date_check_in The date_check_in to set
	 */
	public void setDate_check_in(String date_check_in) {
		this.date_check_in = date_check_in;
	}

	/** 
	 * Returns the people_booking.
	 * @return String
	 */
	public String getPeople_booking() {
		return people_booking;
	}

	/** 
	 * Set the people_booking.
	 * @param people_booking The people_booking to set
	 */
	public void setPeople_booking(String people_booking) {
		this.people_booking = people_booking;
	}
}