/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-23-2015
 * 
 * XDoclet definition:
 * @struts.form name="indexForm"
 */
public class IndexForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	// for slide
	private String slideid,slidepicpath,usablestatus,usabledetail;
	//for welcome
	private String weldetail;
	//for interested
	private String interdetail;
	//for services
	private String serid,serdetail,ser_use,ser_detail,ser_empid;
	//for extensions
	private String ext_id,ext_detail,ext_useid,ext_usedetail,ext_empid;
	//for gallery
	private String gal_id,gal_name,gal_picpath,gal_picstatus;
	//for gallery head
	private String hgal_id,hgal_name,hgal_picpath,hgal_picstatus;
	
	public IndexForm() {};
	public IndexForm(String slideId1, String slidePicpath1, String usableStatus1,
			String usableDetail1) {
		// TODO Auto-generated constructor stub
		if(slideId1 =="gallery"){
			
			this.gal_name = slidePicpath1;this.gal_picpath =usableStatus1;this.gal_picstatus=usableDetail1;
		
		}else if(slideId1 =="hgallery"){
			this.hgal_name = slidePicpath1;this.hgal_picpath =usableStatus1;this.hgal_picstatus=usableDetail1;
		}
		else{
			
		}
			this.slideid = slideId1;
			this.slidepicpath = slidePicpath1;
			this.usablestatus = usableStatus1;
			this.usabledetail = usableDetail1;
		
	}

	public IndexForm(String serId2, String serDetail2, String usableStatus2,
			String usableDetail2, String empid) {
		// TODO Auto-generated constructor stub
		if(serId2 =="gallery"){
			
			this.gal_id=serDetail2;this.gal_name = usableStatus2;this.gal_picpath =usableDetail2;this.gal_picstatus=empid;
		
		}else if(serId2 =="hgallery"){
			this.hgal_id=serDetail2;this.hgal_name = usableStatus2;this.hgal_picpath =usableDetail2;this.hgal_picstatus=empid;
		}
		else{
			
		}
		this.serid = serId2;
		this.serdetail = serDetail2;
		this.ser_use = usableStatus2;
		this.ser_detail = usableDetail2;
		this.ser_empid = empid;
	}
	public IndexForm(String usefor, String extId, String extDetail,
			String usableStatus2, String usableDetail2, String empid) {
		// TODO Auto-generated constructor stub
		if(usefor == "extensions"){
			this.ext_id = extId;this.ext_detail=extDetail;this.ext_useid=usableStatus2;this.ext_usedetail=usableDetail2;this.ext_empid=empid;
		}
	}
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	public String getSlideid() {
		return slideid;
	}
	public void setSlideid(String slideid) {
		this.slideid = slideid;
	}
	public String getSlidepicpath() {
		return slidepicpath;
	}
	public void setSlidepicpath(String slidepicpath) {
		this.slidepicpath = slidepicpath;
	}
	public String getUsablestatus() {
		return usablestatus;
	}
	public void setUsablestatus(String usablestatus) {
		this.usablestatus = usablestatus;
	}
	public String getUsabledetail() {
		return usabledetail;
	}
	public void setUsabledetail(String usabledetail) {
		this.usabledetail = usabledetail;
	}
	public String getWeldetail() {
		return weldetail;
	}
	public void setWeldetail(String weldetail) {
		this.weldetail = weldetail;
	}
	public String getInterdetail() {
		return interdetail;
	}
	public void setInterdetail(String interdetail) {
		this.interdetail = interdetail;
	}
	public String getSerid() {
		return serid;
	}
	public void setSerid(String serid) {
		this.serid = serid;
	}
	public String getSerdetail() {
		return serdetail;
	}
	public void setSerdetail(String serdetail) {
		this.serdetail = serdetail;
	}
	public String getSer_use() {
		return ser_use;
	}
	public void setSer_use(String serUse) {
		ser_use = serUse;
	}
	public String getSer_detail() {
		return ser_detail;
	}
	public void setSer_detail(String serDetail) {
		ser_detail = serDetail;
	}
	public String getSer_empid() {
		return ser_empid;
	}
	public void setSer_empid(String serEmpid) {
		ser_empid = serEmpid;
	}
	public String getExt_id() {
		return ext_id;
	}
	public void setExt_id(String extId) {
		ext_id = extId;
	}
	public String getExt_detail() {
		return ext_detail;
	}
	public void setExt_detail(String extDetail) {
		ext_detail = extDetail;
	}
	public String getExt_useid() {
		return ext_useid;
	}
	public void setExt_useid(String extUseid) {
		ext_useid = extUseid;
	}
	public String getExt_usedetail() {
		return ext_usedetail;
	}
	public void setExt_usedetail(String extUsedetail) {
		ext_usedetail = extUsedetail;
	}
	public String getExt_empid() {
		return ext_empid;
	}
	public void setExt_empid(String extEmpid) {
		ext_empid = extEmpid;
	}
	public String getGal_name() {
		return gal_name;
	}
	public void setGal_name(String galName) {
		gal_name = galName;
	}
	public String getGal_picpath() {
		return gal_picpath;
	}
	public void setGal_picpath(String galPicpath) {
		gal_picpath = galPicpath;
	}
	public String getGal_picstatus() {
		return gal_picstatus;
	}
	public void setGal_picstatus(String galPicstatus) {
		gal_picstatus = galPicstatus;
	}
	public String getHgal_name() {
		return hgal_name;
	}
	public void setHgal_name(String hgalName) {
		hgal_name = hgalName;
	}
	public String getHgal_picpath() {
		return hgal_picpath;
	}
	public void setHgal_picpath(String hgalPicpath) {
		hgal_picpath = hgalPicpath;
	}
	public String getHgal_picstatus() {
		return hgal_picstatus;
	}
	public void setHgal_picstatus(String hgalPicstatus) {
		hgal_picstatus = hgalPicstatus;
	}
	public String getGal_id() {
		return gal_id;
	}
	public void setGal_id(String galId) {
		gal_id = galId;
	}
	public String getHgal_id() {
		return hgal_id;
	}
	public void setHgal_id(String hgalId) {
		hgal_id = hgalId;
	}
}